version: "3.8"

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env-db
    # ports:
    #   - "5432:5432"

  web:
    build: .
    command: gunicorn miltec.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/
      - ./staticfiles:/usr/src/staticfiles
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    env_file: .env
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/usr/src/staticfiles
    ports:
      - 8080:80
    depends_on:
      - web

  frontend:
    build: ./miltec-frontend
    volumes:
      - ./miltec-frontend:/usr/src/miltec-frontend
    ports:
      - 4200:4200
    command: npm run start
    # command: npm start

volumes:
  postgres_data:
  staticfiles:
  miltec-frontend:
