# Generated by Django 3.1.4 on 2021-01-05 21:47

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва товару')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Опис товару')),
                ('details', models.TextField(default='', max_length=5000, verbose_name='Деталі товару')),
                ('article', models.PositiveIntegerField(default=0, verbose_name='Артикль товару')),
                ('sold', models.BooleanField(default=False, verbose_name='Проданий')),
                ('slug', models.SlugField(unique=True, verbose_name='Ім`я товару транслітом')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна для всій відвідувачів')),
                ('price_for_users', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна для зареєстрованих відвідувачів')),
                ('image', models.ImageField(blank=True, height_field='height_field', help_text='Зображення товару', null=True, upload_to=product.models.upload_location, verbose_name='Картинка', width_field='width_field')),
                ('image_large', models.ImageField(blank=True, height_field='height_field', help_text='Зображення товару для детального перегляду', null=True, upload_to=product.models.upload_location2, verbose_name='Велика картинка', width_field='width_field')),
                ('width_field', models.IntegerField(default=0, verbose_name='Ширина картинки в пікселях')),
                ('height_field', models.IntegerField(default=0, verbose_name='Висота картинки в пікселях')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='Категорія товару')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.item', verbose_name='Підкатегорія товару')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
    ]
