# Generated by Django 3.1.4 on 2021-01-05 21:42

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва категорії')),
                ('used', models.BooleanField(default=False, verbose_name='Вживані')),
                ('promotions', models.BooleanField(default=False, verbose_name='Знижені ціни')),
                ('slug', models.SlugField(unique=True, verbose_name='Ім`я категорії транслітом')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('image', models.ImageField(blank=True, height_field='height_field', help_text='Картинка категории', null=True, upload_to=menu.models.upload_location, verbose_name='Картинка', width_field='width_field')),
                ('width_field', models.IntegerField(default=0, verbose_name='Ширина картинки в пікселях')),
                ('height_field', models.IntegerField(default=0, verbose_name='Висота картинки в пікселях')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва пункту')),
                ('used', models.BooleanField(default=False, verbose_name='Вживані')),
                ('promotions', models.BooleanField(default=False, verbose_name='Знижені ціни')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Ім`я категорії транслітом')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Belong model')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.item')),
            ],
            options={
                'verbose_name': 'Пункти категорії',
                'verbose_name_plural': 'Пункти категорій',
                'db_table': 'items',
                'ordering': ['object_id', 'id'],
            },
        ),
    ]
